\n;------------------------------------------------------------------------------
; Clocks individual variables\n
; Clock1 variables\n
Clock1_Label=PST
Clock1_12or24=I
Clock1_Timezone=-8
Clock1_DST=1
; Clock2 variables\n
Clock2_Label=France
Clock2_12or24=I
Clock2_Timezone=1
Clock2_DST=1
; Clock3 variables\n
Clock3_Label=CST
Clock3_12or24=I
Clock3_Timezone=-6
Clock3_DST=1
; Clock4 variables\n
Clock4_Label=EST
Clock4_12or24=I
Clock4_Timezone=-5
Clock4_DST=1
\n;------------------------------------------------------------------------------
; DateAndClocks individual variables\n
; DateAndClock1 variables\n
DateAndClock1_Position_Date=62
DateAndClock1_Position_Time=187
; DateAndClock2 variables\n
DateAndClock2_Position_Date=62
DateAndClock2_Position_Time=187
; DateAndClock3 variables\n
DateAndClock3_Position_Date=62
DateAndClock3_Position_Time=187
; DateAndClock4 variables\n
DateAndClock4_Position_Date=62
DateAndClock4_Position_Time=187
\n;------------------------------------------------------------------------------
; Used by the configurators\n
Clock1_12Select=#BackdropColor#
Clock1_24Select=#ColorClear#
Clock1_DSTOnSelect=#BackdropColor#
Clock1_DSTOffSelect=#BackdropColor#
DateAndClock1_DateLeft=#BackdropColor#
DateAndClock1_DateRight=#ColorClear#
Clock2_12Select=#BackdropColor#
Clock2_24Select=#ColorClear#
Clock2_DSTOnSelect=#BackdropColor#
Clock2_DSTOffSelect=#BackdropColor#
DateAndClock2_DateLeft=#BackdropColor#
DateAndClock2_DateRight=#ColorClear#
Clock3_12Select=#BackdropColor#
Clock3_24Select=#ColorClear#
Clock3_DSTOnSelect=#BackdropColor#
Clock3_DSTOffSelect=#BackdropColor#
DateAndClock3_DateLeft=#BackdropColor#
DateAndClock3_DateRight=#ColorClear#
Clock4_12Select=#BackdropColor#
Clock4_24Select=#ColorClear#
Clock4_DSTOnSelect=#BackdropColor#
Clock4_DSTOffSelect=#BackdropColor#
DateAndClock4_DateLeft=#BackdropColor#
DateAndClock4_DateRight=#ColorClear#
