\n;------------------------------------------------------------------------------
; Colors from the color scheme\n
BackgroundColor=0,0,0,95
TextColor=255,255,255
MeterColor=255,255,255,150
BackdropColor=255,255,255,50
\n;------------------------------------------------------------------------------
; Scales\n
ScaleClock=1
ScaleDate=1
ScaleVolume=1
ScaleDisks=1
ScaleNetwork=1
ScaleUptime=1
ScaleFortune=1
ScaleGpu=1
ScaleCpu=1
ScaleMemory=1
